# Generated by bing chat
# I want a small python program that loop forever,
# check if the file '../shared/go-octave' exists, 
# if yes, runs a system call 'octave crush.m' 
# then deleted the '..'shared/go-octave' file
import os
import time

while True:
    if os.path.exists('/shared/go-octave'):
        os.system('octave crush.m')
        os.remove('/shared/go-octave')
    time.sleep(10)
